gestor_de_projecte_homepage:
    path:     /
    defaults: { _controller: GestorDeProjecteBundle:Default:index }

# referent a persona
# formulari alta persona
login_persona:
    path:     /login
    defaults: { _controller: GestorDeProjecteBundle:Persona:login}

# formulari alta persona
nou_persona:
    path:     /formulariAltaPersona
    defaults: { _controller: GestorDeProjecteBundle:Persona:formulariAltaPersona }

# mostra les dades d'una persona controller Persona funcio mostrarAltaPersona
persona:
    path:     /mostraAltaPersona
    defaults: { _controller: GestorDeProjecteBundle:Persona:mostraAltaPersona }

#mostra una persona per id
una_persona:
    path:     /mostraPersona
    defaults: { _controller: GestorDeProjecteBundle:Persona:mostraPersona }
#esborra una persona per id
esborra_persona:
    path:     /esborraPersona
    defaults: { _controller: GestorDeProjecteBundle:Persona:esborrarPersona}

#modifica una persona 
modificaPersona:
    path:     /modificaPersona
    defaults: { _controller: GestorDeProjecteBundle:Persona:modificaPersona}

#formulari d'alta d'un projecte 
formulariAltaProjecte:
    path:     /formulariAltaProjecte
    defaults: { _controller: GestorDeProjecteBundle:Projecte:formulariAltaProjecte}

admin:
    path:     /admin
    defaults: { _controller: GestorDeProjecteBundle:admin:admin }

cons:
    path:     /cons
    defaults: { _controller: GestorDeProjecteBundle:cons:cons }

consConsuTreb:
    path:     /consConsuTreb
    defaults: { _controller: GestorDeProjecteBundle:consConsuTreb:consConsuTreb }

consConsuProj:
    path:     /consConsuProj
    defaults: { _controller: GestorDeProjecteBundle:consConsuProj:consConsuProj }

consConsuTasq:
    path:     /consConsuTasq
    defaults: { _controller: GestorDeProjecteBundle:consConsuTasq:consConsuTasq }

treb:
    path:     /treb
    defaults: { _controller: GestorDeProjecteBundle:treb:treb }

trebHores:
    path:     /trebHores/{id}
    defaults: { _controller: GestorDeProjecteBundle:trebHores:trebHores }

trebConsProj:
    path:     /trebConsProj
    defaults: { _controller: GestorDeProjecteBundle:trebConsProj:trebConsProj }

trebConsTasq:
    path:     /trebConsProj
    defaults: { _controller: GestorDeProjecteBundle:trebConsProj:trebConsProj }

    