<?php

namespace GestorDeProjecteBundle\Repository;

/**
 * TipusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipusRepository extends \Doctrine\ORM\EntityRepository
{
}
